### ISSUE TITLE
Test.hs does not compile for the Grains excercise

### ISSUE THREAD

**Issue by LadyClaire** [exercism/xhaskell#305] opened 2016-09-18 18:21 UTC
I recieve [this](http://lpaste.net/201757) error message when I run stack test. The problematic code is [here](http://lpaste.net/201759)

**Comment by rbasso** [comment] 2016-09-19 00:37
First of all, thanks for opening this issue! :smile:

I tried to reproduce our problem in my machine, but I couldn't. This is normal and is probably because the solution that I have here is different from yours.

The test suite in `src/Tests.hs` imports `src/Grains.hs` and uses the types of the functions `square` and `total` when resolving its own types. For some reason, this is not working, so it would be useful if you could paste your `src/Grains.hs` here, so that we can reproduce your problem to find a solution.

**Comment by rbasso** [comment] 2016-10-03 05:09
Considering that this PR is pending additional information for two weeks, I'm closing it now.

I'll be reopened if @LadyClaire or anyone else can provide more data to support the hypothesis that there is a problem with the `grain`'s test suite.

**Closed by rbasso** 2016-10-03 05:09 UTC
